"""Add token and status to TenantInvite

Revision ID: a0804c3f320b
Revises: 3ccd5c529fcf
Create Date: 2025-05-10 21:59:18.745022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0804c3f320b'
down_revision: Union[str, None] = '3ccd5c529fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantinvite', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenantinvite', 'status')
    # ### end Alembic commands ###
